/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketPurchaseHistoryRouteImport } from './routes/ticket-purchase-history'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LookupTicketRouteImport } from './routes/lookup-ticket'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as InformationRouteImport } from './routes/information'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard/tickets'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard/invoices'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardBusesRouteImport } from './routes/dashboard/buses'
import { Route as BookingIdRouteImport } from './routes/booking.$id'

const TicketPurchaseHistoryRoute = TicketPurchaseHistoryRouteImport.update({
  id: '/ticket-purchase-history',
  path: '/ticket-purchase-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupTicketRoute = LookupTicketRouteImport.update({
  id: '/lookup-ticket',
  path: '/lookup-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationRoute = InformationRouteImport.update({
  id: '/information',
  path: '/information',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusesRoute = DashboardBusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => DashboardRoute,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/information': typeof InformationRoute
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/lookup-ticket': typeof LookupTicketRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/ticket-purchase-history': typeof TicketPurchaseHistoryRoute
  '/booking/$id': typeof BookingIdRoute
  '/dashboard/buses': typeof DashboardBusesRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/information': typeof InformationRoute
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/lookup-ticket': typeof LookupTicketRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/ticket-purchase-history': typeof TicketPurchaseHistoryRoute
  '/booking/$id': typeof BookingIdRoute
  '/dashboard/buses': typeof DashboardBusesRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/information': typeof InformationRoute
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/lookup-ticket': typeof LookupTicketRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/ticket-purchase-history': typeof TicketPurchaseHistoryRoute
  '/booking/$id': typeof BookingIdRoute
  '/dashboard/buses': typeof DashboardBusesRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/information'
    | '/invoice'
    | '/login'
    | '/lookup-ticket'
    | '/payment'
    | '/register'
    | '/reset-password'
    | '/schedule'
    | '/ticket-purchase-history'
    | '/booking/$id'
    | '/dashboard/buses'
    | '/dashboard/customers'
    | '/dashboard/invoices'
    | '/dashboard/tickets'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/information'
    | '/invoice'
    | '/login'
    | '/lookup-ticket'
    | '/payment'
    | '/register'
    | '/reset-password'
    | '/schedule'
    | '/ticket-purchase-history'
    | '/booking/$id'
    | '/dashboard/buses'
    | '/dashboard/customers'
    | '/dashboard/invoices'
    | '/dashboard/tickets'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/information'
    | '/invoice'
    | '/login'
    | '/lookup-ticket'
    | '/payment'
    | '/register'
    | '/reset-password'
    | '/schedule'
    | '/ticket-purchase-history'
    | '/booking/$id'
    | '/dashboard/buses'
    | '/dashboard/customers'
    | '/dashboard/invoices'
    | '/dashboard/tickets'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InformationRoute: typeof InformationRoute
  InvoiceRoute: typeof InvoiceRoute
  LoginRoute: typeof LoginRoute
  LookupTicketRoute: typeof LookupTicketRoute
  PaymentRoute: typeof PaymentRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  TicketPurchaseHistoryRoute: typeof TicketPurchaseHistoryRoute
  BookingIdRoute: typeof BookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ticket-purchase-history': {
      id: '/ticket-purchase-history'
      path: '/ticket-purchase-history'
      fullPath: '/ticket-purchase-history'
      preLoaderRoute: typeof TicketPurchaseHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup-ticket': {
      id: '/lookup-ticket'
      path: '/lookup-ticket'
      fullPath: '/lookup-ticket'
      preLoaderRoute: typeof LookupTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information': {
      id: '/information'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/buses': {
      id: '/dashboard/buses'
      path: '/buses'
      fullPath: '/dashboard/buses'
      preLoaderRoute: typeof DashboardBusesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBusesRoute: typeof DashboardBusesRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBusesRoute: DashboardBusesRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardTicketsRoute: DashboardTicketsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InformationRoute: InformationRoute,
  InvoiceRoute: InvoiceRoute,
  LoginRoute: LoginRoute,
  LookupTicketRoute: LookupTicketRoute,
  PaymentRoute: PaymentRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  TicketPurchaseHistoryRoute: TicketPurchaseHistoryRoute,
  BookingIdRoute: BookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
